[build]
  publish = "public"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    X-Frame-Options = "DENY"

[[headers]]
  for = "/admin.html"
  [headers.values]
    X-Robots-Tag = "noindex"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
